spring.application.name=saas
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/new
spring.datasource.username=postgres
spring.datasource.password=5432
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
